spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiansk
    username: jiansk
    password: 921521
  thymeleaf:
      #禁用页面缓存--不利于性能
      cache: false
  mvc:
      #配置静态资源路径--否则将通过控制器请求可能报404
      static-path-pattern: /static/**
server:
  port: 8081